[package]
name = "password"
version = "0.1.0"
authors = ["Cole Lawrence <cole@reaktor.com>"]
edition = "2018"

[dependencies]
base64 = "0.10.1"
http_req = { path = "./http_req" }
openssl = "0.10.19"
rpassword = "2.1.0"
percent-encoding = "1.0.1"
