[package]
name = "playbar"
version = "0.1.0"
authors = ["Cole Lawrence <cole@reaktor.com>"]
edition = "2018"

[dependencies]
rodio = { version = "0.8.1", default-features=false, features=["vorbis"]}
cpal = { version = "0.8" }